algoritmo "Soma de dois números inteiros"
var
   v1, v2, soma: inteiro
inicio
      Escreva("Digite um valor: ")
      Leia(v1)
      Escreva("Digite outro valor: ")
      Leia(v2)
      soma <- v1 + v2
      Escreva("A soma entre", v1, " e", v2, " é igual a", soma, ".")
fimalgoritmo
4) Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório
entre eles.
Ex:
Digite um valor: 8
Digite outro valor: 5
A soma entre 8 e 5 é igual a 13.
