algoritmo "Compra de dólares"
var
   reais, dolares: real
inicio
      Escreva("Quantos reais você tem? R$ ")
      Leia(reais)
      dolares <- reais / 3.45
      Escreval("Com R$ ", reais:4:2, " reais é possível comprar US$ ", dolares:4:2, " dólares.")
fimalgoritmo
9) Faça um algoritmo que leia quanto dinheiro uma pessoa tem na carteira (em R$)
e mostre quantos dólares ela pode comprar. Considere US$1,00 = R$3,45.
