algoritmo "Somar intervalo"
var
   cont, soma: inteiro
inicio
      cont <- 6
      Enquanto (cont <= 100) faca
         Se (cont = 100) entao
            Escreva(cont, ".")
         Senao
            Escreva(cont, " + ")
         FimSe
         soma <- soma + cont
         cont <- cont + 2
      FimEnquanto
fimalgoritmo
46) Crie um programa que calcule e mostre na tela o resultado da soma entre 6 +
8 + 10 + 12 + 14 + ... + 98 + 100.

