algoritmo "Leitura e soma de números"
var
   cont, numero, soma: inteiro
inicio
      cont <- 1
      Enquanto (cont <= 7) faca
         Escreva("Informe o", cont, "º número: ")
         Leia(numero)
         soma <- soma + numero
         cont <- cont + 1
      FimEnquanto
      Escreva("A soma dos números informados é ", soma)
fimalgoritmo
48) Faça um programa que leia 7 números inteiros e no final mostre o somatório
entre eles.

