algoritmo "Contar até valor definido"
var
   valor, c: inteiro
inicio
      Escreva("Digite um valor: ")
      Leia(valor)
      c <- 1
      Enquanto (c <= valor) faca
         Escreva(c, " ")
         c <- c + 1
      FimEnquanto
      Escreva("Acabou!")
fimalgoritmo
42) Faça um algoritmo que pergunte ao usuário um número inteiro e positivo
qualquer e mostre uma contagem até esse valor:
Ex: Digite um valor: 35
Contagem: 1 2 3 4 5 6 7 ... 33 34 35 Acabou!
