algoritmo "Preencher vetor"
var
   vet: vetor[0..7] de inteiro
   c: inteiro
inicio
      Para c <- 0 ate 7 faca
           vet[c] <- 999
           Escreva(vet[c])
      FimPara
      Escreval
      Para c <- 0 ate 7 faca
           Escreva(c:3, " ")
      FimPara
fimalgoritmo

71) Faça um programa que preencha automaticamente um vetor numérico com 8
posições, conforme abaixo:
999 999 999 999 999 999 999 999
0 1 2 3 4 5 6 7
