algoritmo "Contagem até valor"
var
   v, c: inteiro
inicio
      Escreva("Digite um valor: ")
      Leia(v)
      Para c <- 0 ate v faca
         Escreva(c, ",")
      FimPara
      Escreva(" FIM!")
fimalgoritmo
67) Faça um programa usando a estrutura “para” que leia um número inteiro
positivo e mostre na tela uma contagem de 0 até o valor digitado:
Ex: Digite um valor: 9
Contagem: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, FIM!
